# This workflow performs functions that must occur before launching all the Python tests
# The cache will detect if any of the extra downloads need an update and, if so, will
# fail the workflow. This is required so a maintainer can manually delete the existing
# cache. Deliberate updates to the cache is important to keep track the health and
# status of the cache instead of automatic updates
# Then launch the Python tests in parallel
#
# In order to support Windows testing, the cache uses the enableCrossOsArchive flag.
# The isofit.data.env (ini) assumes the default location for the cached data is
# ~/.isofit -- however, we can't use this as the path in the cache action because
# Windows doesn't restore it correctly for some reason
# As such, the extras are built in the local working directory and cached there, then
# moved to ~/.isofit after, allowing both Linux and Windows to put the cache into the
# correct locations
#
# This workflow is UNTRUSTED. It will NOT have access to the repo SECRETS, but it is
# allowed to be modified by a PR.

name: Build

on:
  pull_request:
    branches-ignore: ["main", "gh-pages"]
    paths: ["isofit/**", "recipe/*.yml", "pyproject.toml", ".github/**"]

concurrency:
  group: ${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true

jobs:
  # Lint
  black:
    if: "!startsWith(github.event.head_commit.message, 'Merge pull request')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: psf/black@stable
        with:
          src: "./isofit"
          version: "24.2.0"

  # Test building the package
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.25"
          python-version: "3.12"

      - name: Build package
        shell: bash
        run: uv build

      - name: Smoke test (wheel)
        run: uv run --isolated --no-project --with dist/*.whl isofit

      - name: Smoke test (source distribution)
        run: uv run --isolated --no-project --with dist/*.tar.gz isofit

  # Either build the cache or check for updates, fail if updates are needed: does not block tests on failure
  cache:
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      cache_key: ${{ steps.cache_key.outputs.cache_key }}
    steps:
      - name: Compute cache key
        id: cache_key
        run: |
          KEY="${{ contains(github.event.pull_request.body || '', '[rebuild-cache]') && format('extras-{0}', github.run_id) || 'extras' }}"
          echo "cache_key=$KEY" >> $GITHUB_OUTPUT
          echo "Cache Key = $KEY"

      - name: Print concurrency group
        run: echo '${{ github.event.pull_request.head.ref }}'

      - name: Cache Extras
        id: cache-extras
        uses: actions/cache@v4
        with:
          path: .isofit
          key: "${{ steps.cache_key.outputs.cache_key }}"
          restore-keys: |
            extras
          enableCrossOsArchive: true

      - name: Move .isofit
        if: steps.cache-extras.outputs.cache-hit == 'true'
        shell: bash
        run: mv .isofit ~/.isofit

      - uses: actions/checkout@v6
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.25"
          python-version: "3.12"
          activate-environment: true

      - name: Install ISOFIT
        shell: bash
        run: |
          uv sync --extra plots

      - name: Check for Updates
        if: steps.cache-extras.outputs.cache-hit == 'true' && steps.rebuild.outputs.rebuild != 'true'
        shell: bash
        run: |
          # Module must report "[x]" to be detected
          SUMMARY="$(isofit -S validate all)"

          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if echo "$SUMMARY" | grep "\[x]"; then
            MSG="Cache update needed, please request a maintainer to delete the cache-extras then rerun this workflow"

            echo ":x: $MSG" >> $GITHUB_STEP_SUMMARY

            echo "$SUMMARY"
            echo "::error::$MSG"
            exit 1
          else
            MSG="No cache update needed"
            echo ":white_check_mark: $MSG" >> $GITHUB_STEP_SUMMARY
            echo "$MSG"
          fi

      - name: Download Extras
        if: steps.cache-extras.outputs.cache-hit != 'true'
        shell: bash
        run: |
          source .venv/bin/activate

          echo "Downloading extras"
          isofit download all
          isofit download windows --mingw # Needed for Windows
          echo "Building examples"
          isofit build

          # Need to move to local dir so that Windows runners can find it
          mv ~/.isofit .

  # Downstream [on: workflow_run] don't have access to PR num and url, so upload artifact to pass it along
  metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Save PR Metadata
        run: |
          mkdir -p ./metadata
          echo "${{ github.event.number }}" > ./metadata/pr_number.txt
          echo "${{ github.event.pull_request.html_url }}" > ./metadata/pr_url.txt

      - name: Upload PR Metadata
        uses: actions/upload-artifact@v6
        with:
          name: metadata
          path: metadata

  # Test pip installation
  pip:
    needs: cache
    uses: ./.github/workflows/test_pip.yml
    with:
      cache-key: ${{ needs.cache.outputs.cache_key }}

  # Test $PYTHONPATH installation
  path:
    needs: cache
    uses: ./.github/workflows/test_path.yml
    with:
      cache-key: ${{ needs.cache.outputs.cache_key }}

  # Results workflows
  imagecube-small:
    needs: [cache, metadata]
    uses: ./.github/workflows/results_imagecube_small.yml
    with:
      cache-key: ${{ needs.cache.outputs.cache_key }}

  lakemary:
    needs: [cache, metadata]
    uses: ./.github/workflows/results_lakemary.yml
    with:
      cache-key: ${{ needs.cache.outputs.cache_key }}

  seabass:
    needs: [cache, metadata]
    uses: ./.github/workflows/results_seabass.yml
    with:
      cache-key: ${{ needs.cache.outputs.cache_key }}
