name: ImageCube[small] Spectra

on:
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string

permissions:
  contents: read
  pull-requests: write

jobs:
  spectra:
    runs-on: ubuntu-latest
    steps:
      - name: Cached Extras
        id: cache-extras
        uses: actions/cache/restore@v4
        with:
          path: .isofit
          key: ${{ inputs.cache-key }}
          fail-on-cache-miss: true
          enableCrossOsArchive: true

      - name: Move .isofit
        shell: bash
        run: mv .isofit ~/.isofit

      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.25"
          python-version: "3.12"
          activate-environment: true

      - name: Install dependencies
        run: |
          uv sync --extra plots

      - name: Execute tests
        run: |
          mkdir results

          RUN=$(isofit path examples)/image_cube/small/
          $RUN/default.sh --log_file results/default.log --resources

          isoplots spectra $RUN/output/ang20170323t202244_rfl -o results/spectra.png -p 2 4 -p 8 2 -p 5 6 -y -.05 .5
          # isoplots resources results/default.resources.jsonl -o results/default.resources.html -l results/default.log --relative --png --debug

      - uses: actions/upload-artifact@v6
        with:
          name: imagecube_small
          path: results
