# Test a package built and installed by pip.
#
# Test ISOFIT on a variety of versions of Python. This test suite is likely
# sufficient for broadly testing the 'pip' package, with the assumption that
# users are able to get all dependencies installed. Any further testing should
# be for a specific environment, and be very targeted.
#
# For example, testing Ubuntu 22.04 package ecosystem should likely be done by
# building a deb for ISOFIT, and testing against the Python packages provided by
# the apt package repo. It may also be possible to test this environment with a
# mix of upstream packages and a non-isolated virtual environment built with the
# '--system-site-packages' flag.
#
# Readers looking at this file for the purposes of installing ISOFIT on their
# system should be aware that these tests run in an isolated manner. Be aware
# that both 'pip' and 'apt/apt-get' can both be used to install Python
# packages, but pip installing something with Ubuntu's system Python will
# conflict with packages installed via 'apt/apt-get', and produce an environment
# that is difficult to unwind.


name: Test 'pip' Package

on:
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        pytest-flags: ["-m unmarked", "-m slow", "-m examples"]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Pull the cache on every runner
      - name: Cached Extras
        id: cache-extras
        uses: actions/cache/restore@v4
        with:
          path: .isofit
          key: ${{ inputs.cache-key }}
          fail-on-cache-miss: true
          enableCrossOsArchive: true

      - name: Move .isofit
        shell: bash
        run: mv .isofit ~/.isofit

      - uses: actions/checkout@v6
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Print concurrency group
        run: echo '${{ github.event.pull_request.head.ref }}'

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.25"
          python-version: ${{ matrix.python-version }}

      - name: Install ISOFIT
        shell: bash
        run: |
          uv sync --extra test

      # Examples are built for ubuntu runners, Windows needs to rebuild every time
      - name: Format for Windows
        shell: bash
        if: runner.os == 'Windows'
        run: |
          uv run isofit --base ~/.isofit build
          uv run isofit download sixs --make --debug-make

      - name: Execute tests
        shell: bash
        run: |
          # uv raises some errors if not activated beforehand
          source .venv/bin/activate
          pytest -v -s "${{ matrix.pytest-flags }}"
